version: '3.4'
services:
  api:
    image: kgolezardi/performance-review-backend:latest
    depends_on:
      - database
    ports:
      - 8000:8000
    environment:
      - DEBUG
      - SECRET_KEY
      - DATABASE_URL
      - ALLOWED_HOSTS
      - CORS_ALLOW_CREDENTIALS
  database:
    image: postgres:12.1
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - database-data:/var/lib/postgresql/data


volumes:
  database-data:

