version: '3.4'
services:
  api:
    build: ../../review
    depends_on:
      - database
    ports:
      - 8000:8000
    environment: 
      - SECRET_KEY
      - DATABASE_URL
      - ALLOWED_HOSTS
  database:
    image: postgres:12.1
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - database-data:/var/lib/postgresql/data


volumes:
  database-data:

